erm="outputs/data_dir=/vast/hvp2011/data/metashifts/MetaDatasetCatDog/test_data_dir=None/data_transform=AugWaterbirdsCelebATransform/dataset=MetaShiftDataset/alpha=0.0/model=imagenet_resnet50_pretrained/train_from_scratch=False/moo_method=erm/num_tokens=10/multi_prompt=False/n_epochs=50/batch_size=16/lr=0.001/scheduler=False/weight_decay=0.0001/warmup=5/max_grad_norm=1/preference=None/seed=0/log_every=100/save_step=10/save_best=False/save_last=False/output_dir=outputs/data_dir=/vast/hvp2011/data/metashifts/MetaDatasetCatDog/test_data_dir=None/data_transform=AugWaterbirdsCelebATransform/dataset=MetaShiftDataset/alpha=0.0/model=imagenet_resnet50_pretrained/train_from_scratch=False/moo_method=erm/num_tokens=10/multi_prompt=False/n_epochs=50/batch_size=16/lr=0.001/scheduler=False/weight_decay=0.0001/warmup=5/max_grad_norm=1/preference=None/seed=0/log_every=100/save_step=10/save_best=False/save_last=False/best_val.pt"

groupdro="outputs/data_dir=/vast/hvp2011/data/metashifts/MetaDatasetCatDog/test_data_dir=None/data_transform=AugWaterbirdsCelebATransform/dataset=MetaShiftDataset/alpha=1.0/model=imagenet_resnet50_pretrained/train_from_scratch=False/moo_method=groupdro/num_tokens=10/multi_prompt=False/n_epochs=50/batch_size=16/lr=0.001/scheduler=False/weight_decay=0.0001/warmup=5/max_grad_norm=1/preference=None/seed=0/log_every=100/save_step=10/save_best=False/save_last=False/output_dir=outputs/data_dir=/vast/hvp2011/data/metashifts/MetaDatasetCatDog/test_data_dir=None/data_transform=AugWaterbirdsCelebATransform/dataset=MetaShiftDataset/alpha=1.0/model=imagenet_resnet50_pretrained/train_from_scratch=False/moo_method=groupdro/num_tokens=10/multi_prompt=False/n_epochs=50/batch_size=16/lr=0.001/scheduler=False/weight_decay=0.0001/warmup=5/max_grad_norm=1/preference=None/seed=0/log_every=100/save_step=10/save_best=False/save_last=False/best_val.pt"

ours="outputs/data_dir=/vast/hvp2011/data/metashifts/MetaDatasetCatDog/test_data_dir=None/data_transform=AugWaterbirdsCelebATransform/dataset=MetaShiftDataset/alpha=1.2/model=imagenet_resnet50_pretrained/train_from_scratch=False/moo_method=epo/num_tokens=10/multi_prompt=False/n_epochs=50/batch_size=16/lr=0.003/scheduler=False/weight_decay=0.01/warmup=5/max_grad_norm=1/preference=['1', '1', '1', '1']/seed=0/log_every=10/save_step=10/save_best=False/save_last=False/output_dir=outputs/data_dir=/vast/hvp2011/data/metashifts/MetaDatasetCatDog/test_data_dir=None/data_transform=AugWaterbirdsCelebATransform/dataset=MetaShiftDataset/alpha=1.2/model=imagenet_resnet50_pretrained/train_from_scratch=False/moo_method=epo/num_tokens=10/multi_prompt=False/n_epochs=50/batch_size=16/lr=0.003/scheduler=False/weight_decay=0.01/warmup=5/max_grad_norm=1/preference=['1', '1', '1', '1']/seed=0/log_every=10/save_step=10/save_best=False/save_last=False/best_test.pt"

echo ERM $erm
echo GROUPDRO $groupdro
echo OUR $ours

python gradcam.py --model  imagenet_resnet50_pretrained --num_tokens 5 --multi_prompt \
                  --output_dir outputs/gradcam/erm/ --data_dir /vast/hvp2011/data/metashifts/MetaDatasetCatDog \
                  --erm_ckpt $erm --groupdro_ckpt $groupdro --our_ckpt "$ours"